apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-project
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: control-project
  template:
    metadata:
      labels:
        app: control-project
    spec:
      containers:
        - name: control-project
          image: 1230199/control_project:latest
          ports:
            - containerPort: 8080
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: control-project
  namespace: monitoring
  labels:
    app: control-project
spec:
  selector:
    app: control-project
  ports:
    - port: 8000
      targetPort: 8000
      name: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: control-project
  namespace: monitoring
  labels:
    release: Prometheus # Match the release label of your Prometheus instance
spec:
  selector:
    matchLabels:
      app: control-project # Match the labels of your Spring Boot service
  endpoints:
    - port: web # The port name or number where metrics are exposed
      path: /metrics # The path to the metrics endpoint
      interval: 15s # Scrape interval
