apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-project
  namespace: app-namespace-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-project
  template:
    metadata:
      labels:
        app: control-project
    spec:
      containers:
        - name: control-project
          image: 1230199/control_project:latest
          ports:
            - containerPort: 8080
              name: web
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "700m"
---
apiVersion: v1
kind: Service
metadata:
  name: control-project
  namespace: app-namespace-json
  labels:
    app: control-project
spec:
  selector:
    app: control-project
  ports:
    - port: 8080
      targetPort: 8080
      name: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: control-project
  namespace: app-namespace-json
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: control-project
  endpoints:
    - port: web
      path: /actuator/prometheus
      interval: 15s
