apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-project
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: control-project
  template:
    metadata:
      labels:
        app: control-project
    spec:
      containers:
        - name: control-project
          image: 1230199/control_project
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: control-project-svc
spec:
  type: LoadBalancer
  selector:
    app: control-project
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: control-project-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack # Match the release label of your Prometheus instance
spec:
  selector:
    matchLabels:
      app: control-project # Match the labels of your Spring Boot service
  endpoints:
    - port: http # The port name or number where metrics are exposed
      path: /actuator/prometheus # The path to the metrics endpoint
      interval: 15s # Scrape interval
  namespaceSelector:
    matchNames:
      - default
