apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler
spec:
  selector:
    matchLabels:
      app: kepler
  template:
    metadata:
      labels:
        app: kepler
    spec:
      containers:
        - name: kepler
          image: quay.io/sustainable_computing_io/kepler:latest
          ports:
            - containerPort: 9102
---
apiVersion: v1
kind: Service
metadata:
  name: kepler-service
spec:
  selector:
    app: kepler
  ports:
    - protocol: TCP
      port: 9102
      targetPort: 9102
