apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: "control_project"
      metrics_path: "/actuator/prometheus"
      static_configs:
        - targets: ["localhost:8080"] # Should this be localhost for k8?
          labels:
            application: "control_project"
    - job_name: "kepler_exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["localhost:9102"]
          labels:
            application: "kepler_exporter"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-dep
spec:
  selector:
    matchLabels:
      app: prometheus-de
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-de
    spec:
      containers:
        - name: prometheus-dep
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
              name: prometheus-dep
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
spec:
  selector:
    app: prometheus-service
  ports:
    - name: prometheus-service
      protocol: TCP
      port: 9090
      targetPort: 9090
