// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: product_entity.proto
// Protobuf Java Version: 4.29.0

package com.conveniencestore.conveniencestore.protobuf;

public final class ProductEntityOuterClass {
  private ProductEntityOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      ProductEntityOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.LocalDateTime created_at = 3;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.LocalDateTime created_at = 3;</code>
     * @return The createdAt.
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getCreatedAt();
    /**
     * <code>.LocalDateTime created_at = 3;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getCreatedAtOrBuilder();

    /**
     * <code>.LocalDateTime updated_at = 4;</code>
     * @return Whether the updatedAt field is set.
     */
    boolean hasUpdatedAt();
    /**
     * <code>.LocalDateTime updated_at = 4;</code>
     * @return The updatedAt.
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getUpdatedAt();
    /**
     * <code>.LocalDateTime updated_at = 4;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getUpdatedAtOrBuilder();

    /**
     * <code>repeated .Product products = 5;</code>
     */
    java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product> 
        getProductsList();
    /**
     * <code>repeated .Product products = 5;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product getProducts(int index);
    /**
     * <code>repeated .Product products = 5;</code>
     */
    int getProductsCount();
    /**
     * <code>repeated .Product products = 5;</code>
     */
    java.util.List<? extends com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder> 
        getProductsOrBuilderList();
    /**
     * <code>repeated .Product products = 5;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder getProductsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProductEntity}
   */
  public static final class ProductEntity extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProductEntity)
      ProductEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        ProductEntity.class.getName());
    }
    // Use ProductEntity.newBuilder() to construct.
    private ProductEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProductEntity() {
      name_ = "";
      products_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.class, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_AT_FIELD_NUMBER = 3;
    private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime createdAt_;
    /**
     * <code>.LocalDateTime created_at = 3;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.LocalDateTime created_at = 3;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getCreatedAt() {
      return createdAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.LocalDateTime created_at = 3;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getCreatedAtOrBuilder() {
      return createdAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 4;
    private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime updatedAt_;
    /**
     * <code>.LocalDateTime updated_at = 4;</code>
     * @return Whether the updatedAt field is set.
     */
    @java.lang.Override
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.LocalDateTime updated_at = 4;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getUpdatedAt() {
      return updatedAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.LocalDateTime updated_at = 4;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getUpdatedAtOrBuilder() {
      return updatedAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
    }

    public static final int PRODUCTS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product> products_;
    /**
     * <code>repeated .Product products = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product> getProductsList() {
      return products_;
    }
    /**
     * <code>repeated .Product products = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder> 
        getProductsOrBuilderList() {
      return products_;
    }
    /**
     * <code>repeated .Product products = 5;</code>
     */
    @java.lang.Override
    public int getProductsCount() {
      return products_.size();
    }
    /**
     * <code>repeated .Product products = 5;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product getProducts(int index) {
      return products_.get(index);
    }
    /**
     * <code>repeated .Product products = 5;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder getProductsOrBuilder(
        int index) {
      return products_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(4, getUpdatedAt());
      }
      for (int i = 0; i < products_.size(); i++) {
        output.writeMessage(5, products_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getUpdatedAt());
      }
      for (int i = 0; i < products_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, products_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity)) {
        return super.equals(obj);
      }
      com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity other = (com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
      if (hasUpdatedAt()) {
        if (!getUpdatedAt()
            .equals(other.getUpdatedAt())) return false;
      }
      if (!getProductsList()
          .equals(other.getProductsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      if (hasUpdatedAt()) {
        hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedAt().hashCode();
      }
      if (getProductsCount() > 0) {
        hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
        hash = (53 * hash) + getProductsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductEntity)
        com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.class, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder.class);
      }

      // Construct using com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getCreatedAtFieldBuilder();
          getUpdatedAtFieldBuilder();
          getProductsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        updatedAt_ = null;
        if (updatedAtBuilder_ != null) {
          updatedAtBuilder_.dispose();
          updatedAtBuilder_ = null;
        }
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
        } else {
          products_ = null;
          productsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntity_descriptor;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity getDefaultInstanceForType() {
        return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.getDefaultInstance();
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity build() {
        com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity buildPartial() {
        com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity result = new com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity result) {
        if (productsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            products_ = java.util.Collections.unmodifiableList(products_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.products_ = products_;
        } else {
          result.products_ = productsBuilder_.build();
        }
      }

      private void buildPartial0(com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.createdAt_ = createdAtBuilder_ == null
              ? createdAt_
              : createdAtBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.updatedAt_ = updatedAtBuilder_ == null
              ? updatedAt_
              : updatedAtBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity) {
          return mergeFrom((com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity other) {
        if (other == com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        if (other.hasUpdatedAt()) {
          mergeUpdatedAt(other.getUpdatedAt());
        }
        if (productsBuilder_ == null) {
          if (!other.products_.isEmpty()) {
            if (products_.isEmpty()) {
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureProductsIsMutable();
              products_.addAll(other.products_);
            }
            onChanged();
          }
        } else {
          if (!other.products_.isEmpty()) {
            if (productsBuilder_.isEmpty()) {
              productsBuilder_.dispose();
              productsBuilder_ = null;
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000010);
              productsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProductsFieldBuilder() : null;
            } else {
              productsBuilder_.addAllMessages(other.products_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getCreatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getUpdatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product m =
                    input.readMessage(
                        com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.parser(),
                        extensionRegistry);
                if (productsBuilder_ == null) {
                  ensureProductsIsMutable();
                  products_.add(m);
                } else {
                  productsBuilder_.addMessage(m);
                }
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime createdAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> createdAtBuilder_;
      /**
       * <code>.LocalDateTime created_at = 3;</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.LocalDateTime created_at = 3;</code>
       * @return The createdAt.
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.LocalDateTime created_at = 3;</code>
       */
      public Builder setCreatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
        } else {
          createdAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 3;</code>
       */
      public Builder setCreatedAt(
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 3;</code>
       */
      public Builder mergeCreatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (createdAtBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            createdAt_ != null &&
            createdAt_ != com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance()) {
            getCreatedAtBuilder().mergeFrom(value);
          } else {
            createdAt_ = value;
          }
        } else {
          createdAtBuilder_.mergeFrom(value);
        }
        if (createdAt_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 3;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 3;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder getCreatedAtBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.LocalDateTime created_at = 3;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <code>.LocalDateTime created_at = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> 
          getCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }

      private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime updatedAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> updatedAtBuilder_;
      /**
       * <code>.LocalDateTime updated_at = 4;</code>
       * @return Whether the updatedAt field is set.
       */
      public boolean hasUpdatedAt() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.LocalDateTime updated_at = 4;</code>
       * @return The updatedAt.
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          return updatedAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
        } else {
          return updatedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.LocalDateTime updated_at = 4;</code>
       */
      public Builder setUpdatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (updatedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updatedAt_ = value;
        } else {
          updatedAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 4;</code>
       */
      public Builder setUpdatedAt(
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder builderForValue) {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = builderForValue.build();
        } else {
          updatedAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 4;</code>
       */
      public Builder mergeUpdatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (updatedAtBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            updatedAt_ != null &&
            updatedAt_ != com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance()) {
            getUpdatedAtBuilder().mergeFrom(value);
          } else {
            updatedAt_ = value;
          }
        } else {
          updatedAtBuilder_.mergeFrom(value);
        }
        if (updatedAt_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 4;</code>
       */
      public Builder clearUpdatedAt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        updatedAt_ = null;
        if (updatedAtBuilder_ != null) {
          updatedAtBuilder_.dispose();
          updatedAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 4;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder getUpdatedAtBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getUpdatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.LocalDateTime updated_at = 4;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getUpdatedAtOrBuilder() {
        if (updatedAtBuilder_ != null) {
          return updatedAtBuilder_.getMessageOrBuilder();
        } else {
          return updatedAt_ == null ?
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
        }
      }
      /**
       * <code>.LocalDateTime updated_at = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> 
          getUpdatedAtFieldBuilder() {
        if (updatedAtBuilder_ == null) {
          updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder>(
                  getUpdatedAt(),
                  getParentForChildren(),
                  isClean());
          updatedAt_ = null;
        }
        return updatedAtBuilder_;
      }

      private java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product> products_ =
        java.util.Collections.emptyList();
      private void ensureProductsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          products_ = new java.util.ArrayList<com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product>(products_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder> productsBuilder_;

      /**
       * <code>repeated .Product products = 5;</code>
       */
      public java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product> getProductsList() {
        if (productsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(products_);
        } else {
          return productsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public int getProductsCount() {
        if (productsBuilder_ == null) {
          return products_.size();
        } else {
          return productsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product getProducts(int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);
        } else {
          return productsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public Builder setProducts(
          int index, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.set(index, value);
          onChanged();
        } else {
          productsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public Builder setProducts(
          int index, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.set(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public Builder addProducts(com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(value);
          onChanged();
        } else {
          productsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public Builder addProducts(
          int index, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(index, value);
          onChanged();
        } else {
          productsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public Builder addProducts(
          com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public Builder addProducts(
          int index, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public Builder addAllProducts(
          java.lang.Iterable<? extends com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product> values) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, products_);
          onChanged();
        } else {
          productsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public Builder clearProducts() {
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          productsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public Builder removeProducts(int index) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.remove(index);
          onChanged();
        } else {
          productsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder getProductsBuilder(
          int index) {
        return getProductsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder getProductsOrBuilder(
          int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);  } else {
          return productsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public java.util.List<? extends com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder> 
           getProductsOrBuilderList() {
        if (productsBuilder_ != null) {
          return productsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(products_);
        }
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder addProductsBuilder() {
        return getProductsFieldBuilder().addBuilder(
            com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder addProductsBuilder(
          int index) {
        return getProductsFieldBuilder().addBuilder(
            index, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product products = 5;</code>
       */
      public java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder> 
           getProductsBuilderList() {
        return getProductsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder> 
          getProductsFieldBuilder() {
        if (productsBuilder_ == null) {
          productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder>(
                  products_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          products_ = null;
        }
        return productsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProductEntity)
    }

    // @@protoc_insertion_point(class_scope:ProductEntity)
    private static final com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity();
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductEntity>
        PARSER = new com.google.protobuf.AbstractParser<ProductEntity>() {
      @java.lang.Override
      public ProductEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProductEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductEntity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductEntityCatalogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductEntityCatalog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity> 
        getProductsList();
    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity getProducts(int index);
    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    int getProductsCount();
    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    java.util.List<? extends com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder> 
        getProductsOrBuilderList();
    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder getProductsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProductEntityCatalog}
   */
  public static final class ProductEntityCatalog extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProductEntityCatalog)
      ProductEntityCatalogOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        ProductEntityCatalog.class.getName());
    }
    // Use ProductEntityCatalog.newBuilder() to construct.
    private ProductEntityCatalog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProductEntityCatalog() {
      products_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntityCatalog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntityCatalog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog.class, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog.Builder.class);
    }

    public static final int PRODUCTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity> products_;
    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity> getProductsList() {
      return products_;
    }
    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder> 
        getProductsOrBuilderList() {
      return products_;
    }
    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    @java.lang.Override
    public int getProductsCount() {
      return products_.size();
    }
    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity getProducts(int index) {
      return products_.get(index);
    }
    /**
     * <code>repeated .ProductEntity products = 1;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder getProductsOrBuilder(
        int index) {
      return products_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < products_.size(); i++) {
        output.writeMessage(1, products_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < products_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, products_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog)) {
        return super.equals(obj);
      }
      com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog other = (com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog) obj;

      if (!getProductsList()
          .equals(other.getProductsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductsCount() > 0) {
        hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
        hash = (53 * hash) + getProductsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductEntityCatalog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductEntityCatalog)
        com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntityCatalog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntityCatalog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog.class, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog.Builder.class);
      }

      // Construct using com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
        } else {
          products_ = null;
          productsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.internal_static_ProductEntityCatalog_descriptor;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog getDefaultInstanceForType() {
        return com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog.getDefaultInstance();
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog build() {
        com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog buildPartial() {
        com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog result = new com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog result) {
        if (productsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            products_ = java.util.Collections.unmodifiableList(products_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.products_ = products_;
        } else {
          result.products_ = productsBuilder_.build();
        }
      }

      private void buildPartial0(com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog) {
          return mergeFrom((com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog other) {
        if (other == com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog.getDefaultInstance()) return this;
        if (productsBuilder_ == null) {
          if (!other.products_.isEmpty()) {
            if (products_.isEmpty()) {
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductsIsMutable();
              products_.addAll(other.products_);
            }
            onChanged();
          }
        } else {
          if (!other.products_.isEmpty()) {
            if (productsBuilder_.isEmpty()) {
              productsBuilder_.dispose();
              productsBuilder_ = null;
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProductsFieldBuilder() : null;
            } else {
              productsBuilder_.addAllMessages(other.products_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity m =
                    input.readMessage(
                        com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.parser(),
                        extensionRegistry);
                if (productsBuilder_ == null) {
                  ensureProductsIsMutable();
                  products_.add(m);
                } else {
                  productsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity> products_ =
        java.util.Collections.emptyList();
      private void ensureProductsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          products_ = new java.util.ArrayList<com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity>(products_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder> productsBuilder_;

      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity> getProductsList() {
        if (productsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(products_);
        } else {
          return productsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public int getProductsCount() {
        if (productsBuilder_ == null) {
          return products_.size();
        } else {
          return productsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity getProducts(int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);
        } else {
          return productsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public Builder setProducts(
          int index, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.set(index, value);
          onChanged();
        } else {
          productsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public Builder setProducts(
          int index, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.set(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public Builder addProducts(com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(value);
          onChanged();
        } else {
          productsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public Builder addProducts(
          int index, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(index, value);
          onChanged();
        } else {
          productsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public Builder addProducts(
          com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public Builder addProducts(
          int index, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public Builder addAllProducts(
          java.lang.Iterable<? extends com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity> values) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, products_);
          onChanged();
        } else {
          productsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public Builder clearProducts() {
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public Builder removeProducts(int index) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.remove(index);
          onChanged();
        } else {
          productsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder getProductsBuilder(
          int index) {
        return getProductsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder getProductsOrBuilder(
          int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);  } else {
          return productsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public java.util.List<? extends com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder> 
           getProductsOrBuilderList() {
        if (productsBuilder_ != null) {
          return productsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(products_);
        }
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder addProductsBuilder() {
        return getProductsFieldBuilder().addBuilder(
            com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder addProductsBuilder(
          int index) {
        return getProductsFieldBuilder().addBuilder(
            index, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductEntity products = 1;</code>
       */
      public java.util.List<com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder> 
           getProductsBuilderList() {
        return getProductsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder> 
          getProductsFieldBuilder() {
        if (productsBuilder_ == null) {
          productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntity.Builder, com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityOrBuilder>(
                  products_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          products_ = null;
        }
        return productsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProductEntityCatalog)
    }

    // @@protoc_insertion_point(class_scope:ProductEntityCatalog)
    private static final com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog();
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductEntityCatalog>
        PARSER = new com.google.protobuf.AbstractParser<ProductEntityCatalog>() {
      @java.lang.Override
      public ProductEntityCatalog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProductEntityCatalog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductEntityCatalog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.ProductEntityOuterClass.ProductEntityCatalog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductEntityCatalog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductEntityCatalog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024product_entity.proto\032\025local_date_time." +
      "proto\032\rproduct.proto\"\215\001\n\rProductEntity\022\n" +
      "\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\"\n\ncreated_at\030\003" +
      " \001(\0132\016.LocalDateTime\022\"\n\nupdated_at\030\004 \001(\013" +
      "2\016.LocalDateTime\022\032\n\010products\030\005 \003(\0132\010.Pro" +
      "duct\"8\n\024ProductEntityCatalog\022 \n\010products" +
      "\030\001 \003(\0132\016.ProductEntityB0\n.com.convenienc" +
      "estore.conveniencestore.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.getDescriptor(),
          com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.getDescriptor(),
        });
    internal_static_ProductEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProductEntity_descriptor,
        new java.lang.String[] { "Id", "Name", "CreatedAt", "UpdatedAt", "Products", });
    internal_static_ProductEntityCatalog_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductEntityCatalog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProductEntityCatalog_descriptor,
        new java.lang.String[] { "Products", });
    descriptor.resolveAllFeaturesImmutable();
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.getDescriptor();
    com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
