// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: product.proto
// Protobuf Java Version: 4.29.0

package com.conveniencestore.conveniencestore.protobuf;

public final class ProductOuterClass {
  private ProductOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      ProductOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 entity_id = 2;</code>
     * @return The entityId.
     */
    int getEntityId();

    /**
     * <code>bool sold = 3;</code>
     * @return The sold.
     */
    boolean getSold();

    /**
     * <code>.LocalDateTime created_at = 4;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.LocalDateTime created_at = 4;</code>
     * @return The createdAt.
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getCreatedAt();
    /**
     * <code>.LocalDateTime created_at = 4;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getCreatedAtOrBuilder();

    /**
     * <code>.LocalDateTime updated_at = 5;</code>
     * @return Whether the updatedAt field is set.
     */
    boolean hasUpdatedAt();
    /**
     * <code>.LocalDateTime updated_at = 5;</code>
     * @return The updatedAt.
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getUpdatedAt();
    /**
     * <code>.LocalDateTime updated_at = 5;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getUpdatedAtOrBuilder();
  }
  /**
   * Protobuf type {@code Product}
   */
  public static final class Product extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        Product.class.getName());
    }
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Product() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.internal_static_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.class, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int ENTITY_ID_FIELD_NUMBER = 2;
    private int entityId_ = 0;
    /**
     * <code>int32 entity_id = 2;</code>
     * @return The entityId.
     */
    @java.lang.Override
    public int getEntityId() {
      return entityId_;
    }

    public static final int SOLD_FIELD_NUMBER = 3;
    private boolean sold_ = false;
    /**
     * <code>bool sold = 3;</code>
     * @return The sold.
     */
    @java.lang.Override
    public boolean getSold() {
      return sold_;
    }

    public static final int CREATED_AT_FIELD_NUMBER = 4;
    private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime createdAt_;
    /**
     * <code>.LocalDateTime created_at = 4;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.LocalDateTime created_at = 4;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getCreatedAt() {
      return createdAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.LocalDateTime created_at = 4;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getCreatedAtOrBuilder() {
      return createdAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 5;
    private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime updatedAt_;
    /**
     * <code>.LocalDateTime updated_at = 5;</code>
     * @return Whether the updatedAt field is set.
     */
    @java.lang.Override
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.LocalDateTime updated_at = 5;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getUpdatedAt() {
      return updatedAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.LocalDateTime updated_at = 5;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getUpdatedAtOrBuilder() {
      return updatedAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (entityId_ != 0) {
        output.writeInt32(2, entityId_);
      }
      if (sold_ != false) {
        output.writeBool(3, sold_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(5, getUpdatedAt());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (entityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, entityId_);
      }
      if (sold_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, sold_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getUpdatedAt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product)) {
        return super.equals(obj);
      }
      com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product other = (com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product) obj;

      if (getId()
          != other.getId()) return false;
      if (getEntityId()
          != other.getEntityId()) return false;
      if (getSold()
          != other.getSold()) return false;
      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
      if (hasUpdatedAt()) {
        if (!getUpdatedAt()
            .equals(other.getUpdatedAt())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ENTITY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEntityId();
      hash = (37 * hash) + SOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSold());
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      if (hasUpdatedAt()) {
        hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedAt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Product)
        com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.internal_static_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.internal_static_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.class, com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.Builder.class);
      }

      // Construct using com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getCreatedAtFieldBuilder();
          getUpdatedAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        entityId_ = 0;
        sold_ = false;
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        updatedAt_ = null;
        if (updatedAtBuilder_ != null) {
          updatedAtBuilder_.dispose();
          updatedAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.internal_static_Product_descriptor;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product getDefaultInstanceForType() {
        return com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.getDefaultInstance();
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product build() {
        com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product buildPartial() {
        com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product result = new com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.entityId_ = entityId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sold_ = sold_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.createdAt_ = createdAtBuilder_ == null
              ? createdAt_
              : createdAtBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.updatedAt_ = updatedAtBuilder_ == null
              ? updatedAt_
              : updatedAtBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product) {
          return mergeFrom((com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product other) {
        if (other == com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getEntityId() != 0) {
          setEntityId(other.getEntityId());
        }
        if (other.getSold() != false) {
          setSold(other.getSold());
        }
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        if (other.hasUpdatedAt()) {
          mergeUpdatedAt(other.getUpdatedAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                entityId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                sold_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                input.readMessage(
                    getCreatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getUpdatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int entityId_ ;
      /**
       * <code>int32 entity_id = 2;</code>
       * @return The entityId.
       */
      @java.lang.Override
      public int getEntityId() {
        return entityId_;
      }
      /**
       * <code>int32 entity_id = 2;</code>
       * @param value The entityId to set.
       * @return This builder for chaining.
       */
      public Builder setEntityId(int value) {

        entityId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 entity_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntityId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        entityId_ = 0;
        onChanged();
        return this;
      }

      private boolean sold_ ;
      /**
       * <code>bool sold = 3;</code>
       * @return The sold.
       */
      @java.lang.Override
      public boolean getSold() {
        return sold_;
      }
      /**
       * <code>bool sold = 3;</code>
       * @param value The sold to set.
       * @return This builder for chaining.
       */
      public Builder setSold(boolean value) {

        sold_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool sold = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSold() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sold_ = false;
        onChanged();
        return this;
      }

      private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime createdAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> createdAtBuilder_;
      /**
       * <code>.LocalDateTime created_at = 4;</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.LocalDateTime created_at = 4;</code>
       * @return The createdAt.
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.LocalDateTime created_at = 4;</code>
       */
      public Builder setCreatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
        } else {
          createdAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 4;</code>
       */
      public Builder setCreatedAt(
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 4;</code>
       */
      public Builder mergeCreatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (createdAtBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            createdAt_ != null &&
            createdAt_ != com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance()) {
            getCreatedAtBuilder().mergeFrom(value);
          } else {
            createdAt_ = value;
          }
        } else {
          createdAtBuilder_.mergeFrom(value);
        }
        if (createdAt_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 4;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 4;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder getCreatedAtBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.LocalDateTime created_at = 4;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <code>.LocalDateTime created_at = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> 
          getCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }

      private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime updatedAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> updatedAtBuilder_;
      /**
       * <code>.LocalDateTime updated_at = 5;</code>
       * @return Whether the updatedAt field is set.
       */
      public boolean hasUpdatedAt() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.LocalDateTime updated_at = 5;</code>
       * @return The updatedAt.
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          return updatedAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
        } else {
          return updatedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.LocalDateTime updated_at = 5;</code>
       */
      public Builder setUpdatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (updatedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updatedAt_ = value;
        } else {
          updatedAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 5;</code>
       */
      public Builder setUpdatedAt(
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder builderForValue) {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = builderForValue.build();
        } else {
          updatedAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 5;</code>
       */
      public Builder mergeUpdatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (updatedAtBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            updatedAt_ != null &&
            updatedAt_ != com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance()) {
            getUpdatedAtBuilder().mergeFrom(value);
          } else {
            updatedAt_ = value;
          }
        } else {
          updatedAtBuilder_.mergeFrom(value);
        }
        if (updatedAt_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 5;</code>
       */
      public Builder clearUpdatedAt() {
        bitField0_ = (bitField0_ & ~0x00000010);
        updatedAt_ = null;
        if (updatedAtBuilder_ != null) {
          updatedAtBuilder_.dispose();
          updatedAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 5;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder getUpdatedAtBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getUpdatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.LocalDateTime updated_at = 5;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getUpdatedAtOrBuilder() {
        if (updatedAtBuilder_ != null) {
          return updatedAtBuilder_.getMessageOrBuilder();
        } else {
          return updatedAt_ == null ?
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
        }
      }
      /**
       * <code>.LocalDateTime updated_at = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> 
          getUpdatedAtFieldBuilder() {
        if (updatedAtBuilder_ == null) {
          updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder>(
                  getUpdatedAt(),
                  getParentForChildren(),
                  isClean());
          updatedAt_ = null;
        }
        return updatedAtBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Product)
    }

    // @@protoc_insertion_point(class_scope:Product)
    private static final com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product();
    }

    public static com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.ProductOuterClass.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\032\025local_date_time.proto\"~" +
      "\n\007Product\022\n\n\002id\030\001 \001(\005\022\021\n\tentity_id\030\002 \001(\005" +
      "\022\014\n\004sold\030\003 \001(\010\022\"\n\ncreated_at\030\004 \001(\0132\016.Loc" +
      "alDateTime\022\"\n\nupdated_at\030\005 \001(\0132\016.LocalDa" +
      "teTimeB0\n.com.conveniencestore.convenien" +
      "cestore.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.getDescriptor(),
        });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "Id", "EntityId", "Sold", "CreatedAt", "UpdatedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
