// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_response_dto.proto
// Protobuf Java Version: 4.29.0

package com.conveniencestore.conveniencestore.protobuf;

public final class UserResponseDto {
  private UserResponseDto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      UserResponseDto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserResponseDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserResponseDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string username = 2;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.UserRoles role = 4;</code>
     * @return The enum numeric value on the wire for role.
     */
    int getRoleValue();
    /**
     * <code>.UserRoles role = 4;</code>
     * @return The role.
     */
    com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles getRole();

    /**
     * <code>.LocalDateTime created_at = 5;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.LocalDateTime created_at = 5;</code>
     * @return The createdAt.
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getCreatedAt();
    /**
     * <code>.LocalDateTime created_at = 5;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getCreatedAtOrBuilder();

    /**
     * <code>.LocalDateTime updated_at = 6;</code>
     * @return Whether the updatedAt field is set.
     */
    boolean hasUpdatedAt();
    /**
     * <code>.LocalDateTime updated_at = 6;</code>
     * @return The updatedAt.
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getUpdatedAt();
    /**
     * <code>.LocalDateTime updated_at = 6;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getUpdatedAtOrBuilder();
  }
  /**
   * Protobuf type {@code UserResponseDTO}
   */
  public static final class UserResponseDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserResponseDTO)
      UserResponseDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        UserResponseDTO.class.getName());
    }
    // Use UserResponseDTO.newBuilder() to construct.
    private UserResponseDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserResponseDTO() {
      username_ = "";
      email_ = "";
      role_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.class, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object username_ = "";
    /**
     * <code>string username = 2;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROLE_FIELD_NUMBER = 4;
    private int role_ = 0;
    /**
     * <code>.UserRoles role = 4;</code>
     * @return The enum numeric value on the wire for role.
     */
    @java.lang.Override public int getRoleValue() {
      return role_;
    }
    /**
     * <code>.UserRoles role = 4;</code>
     * @return The role.
     */
    @java.lang.Override public com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles getRole() {
      com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles result = com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles.forNumber(role_);
      return result == null ? com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles.UNRECOGNIZED : result;
    }

    public static final int CREATED_AT_FIELD_NUMBER = 5;
    private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime createdAt_;
    /**
     * <code>.LocalDateTime created_at = 5;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.LocalDateTime created_at = 5;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getCreatedAt() {
      return createdAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.LocalDateTime created_at = 5;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getCreatedAtOrBuilder() {
      return createdAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 6;
    private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime updatedAt_;
    /**
     * <code>.LocalDateTime updated_at = 6;</code>
     * @return Whether the updatedAt field is set.
     */
    @java.lang.Override
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.LocalDateTime updated_at = 6;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getUpdatedAt() {
      return updatedAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.LocalDateTime updated_at = 6;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getUpdatedAtOrBuilder() {
      return updatedAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, email_);
      }
      if (role_ != com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles.ADMIN.getNumber()) {
        output.writeEnum(4, role_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(6, getUpdatedAt());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, email_);
      }
      if (role_ != com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles.ADMIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, role_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCreatedAt());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getUpdatedAt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO)) {
        return super.equals(obj);
      }
      com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO other = (com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (role_ != other.role_) return false;
      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
      if (hasUpdatedAt()) {
        if (!getUpdatedAt()
            .equals(other.getUpdatedAt())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + ROLE_FIELD_NUMBER;
      hash = (53 * hash) + role_;
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      if (hasUpdatedAt()) {
        hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedAt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserResponseDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserResponseDTO)
        com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.class, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder.class);
      }

      // Construct using com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getCreatedAtFieldBuilder();
          getUpdatedAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        username_ = "";
        email_ = "";
        role_ = 0;
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        updatedAt_ = null;
        if (updatedAtBuilder_ != null) {
          updatedAtBuilder_.dispose();
          updatedAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseDTO_descriptor;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO getDefaultInstanceForType() {
        return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO build() {
        com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO buildPartial() {
        com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO result = new com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.role_ = role_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.createdAt_ = createdAtBuilder_ == null
              ? createdAt_
              : createdAtBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.updatedAt_ = updatedAtBuilder_ == null
              ? updatedAt_
              : updatedAtBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO) {
          return mergeFrom((com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO other) {
        if (other == com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.role_ != 0) {
          setRoleValue(other.getRoleValue());
        }
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        if (other.hasUpdatedAt()) {
          mergeUpdatedAt(other.getUpdatedAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                role_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                input.readMessage(
                    getCreatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getUpdatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 2;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int role_ = 0;
      /**
       * <code>.UserRoles role = 4;</code>
       * @return The enum numeric value on the wire for role.
       */
      @java.lang.Override public int getRoleValue() {
        return role_;
      }
      /**
       * <code>.UserRoles role = 4;</code>
       * @param value The enum numeric value on the wire for role to set.
       * @return This builder for chaining.
       */
      public Builder setRoleValue(int value) {
        role_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.UserRoles role = 4;</code>
       * @return The role.
       */
      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles getRole() {
        com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles result = com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles.forNumber(role_);
        return result == null ? com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles.UNRECOGNIZED : result;
      }
      /**
       * <code>.UserRoles role = 4;</code>
       * @param value The role to set.
       * @return This builder for chaining.
       */
      public Builder setRole(com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.UserRoles value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        role_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.UserRoles role = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRole() {
        bitField0_ = (bitField0_ & ~0x00000008);
        role_ = 0;
        onChanged();
        return this;
      }

      private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime createdAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> createdAtBuilder_;
      /**
       * <code>.LocalDateTime created_at = 5;</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.LocalDateTime created_at = 5;</code>
       * @return The createdAt.
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.LocalDateTime created_at = 5;</code>
       */
      public Builder setCreatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
        } else {
          createdAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 5;</code>
       */
      public Builder setCreatedAt(
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 5;</code>
       */
      public Builder mergeCreatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (createdAtBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            createdAt_ != null &&
            createdAt_ != com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance()) {
            getCreatedAtBuilder().mergeFrom(value);
          } else {
            createdAt_ = value;
          }
        } else {
          createdAtBuilder_.mergeFrom(value);
        }
        if (createdAt_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 5;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000010);
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime created_at = 5;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder getCreatedAtBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.LocalDateTime created_at = 5;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <code>.LocalDateTime created_at = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> 
          getCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }

      private com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime updatedAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> updatedAtBuilder_;
      /**
       * <code>.LocalDateTime updated_at = 6;</code>
       * @return Whether the updatedAt field is set.
       */
      public boolean hasUpdatedAt() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.LocalDateTime updated_at = 6;</code>
       * @return The updatedAt.
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime getUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          return updatedAt_ == null ? com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
        } else {
          return updatedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.LocalDateTime updated_at = 6;</code>
       */
      public Builder setUpdatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (updatedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updatedAt_ = value;
        } else {
          updatedAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 6;</code>
       */
      public Builder setUpdatedAt(
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder builderForValue) {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = builderForValue.build();
        } else {
          updatedAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 6;</code>
       */
      public Builder mergeUpdatedAt(com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime value) {
        if (updatedAtBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            updatedAt_ != null &&
            updatedAt_ != com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance()) {
            getUpdatedAtBuilder().mergeFrom(value);
          } else {
            updatedAt_ = value;
          }
        } else {
          updatedAtBuilder_.mergeFrom(value);
        }
        if (updatedAt_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 6;</code>
       */
      public Builder clearUpdatedAt() {
        bitField0_ = (bitField0_ & ~0x00000020);
        updatedAt_ = null;
        if (updatedAtBuilder_ != null) {
          updatedAtBuilder_.dispose();
          updatedAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.LocalDateTime updated_at = 6;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder getUpdatedAtBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getUpdatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.LocalDateTime updated_at = 6;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder getUpdatedAtOrBuilder() {
        if (updatedAtBuilder_ != null) {
          return updatedAtBuilder_.getMessageOrBuilder();
        } else {
          return updatedAt_ == null ?
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.getDefaultInstance() : updatedAt_;
        }
      }
      /**
       * <code>.LocalDateTime updated_at = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder> 
          getUpdatedAtFieldBuilder() {
        if (updatedAtBuilder_ == null) {
          updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTime.Builder, com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.LocalDateTimeOrBuilder>(
                  getUpdatedAt(),
                  getParentForChildren(),
                  isClean());
          updatedAt_ = null;
        }
        return updatedAtBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:UserResponseDTO)
    }

    // @@protoc_insertion_point(class_scope:UserResponseDTO)
    private static final com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO();
    }

    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserResponseDTO>
        PARSER = new com.google.protobuf.AbstractParser<UserResponseDTO>() {
      @java.lang.Override
      public UserResponseDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserResponseDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserResponseDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserResponseCatalogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserResponseCatalog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    java.util.List<com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO> 
        getUsersList();
    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO getUsers(int index);
    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    int getUsersCount();
    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    java.util.List<? extends com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder> 
        getUsersOrBuilderList();
    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder getUsersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code UserResponseCatalog}
   */
  public static final class UserResponseCatalog extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserResponseCatalog)
      UserResponseCatalogOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        UserResponseCatalog.class.getName());
    }
    // Use UserResponseCatalog.newBuilder() to construct.
    private UserResponseCatalog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserResponseCatalog() {
      users_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseCatalog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseCatalog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog.class, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog.Builder.class);
    }

    public static final int USERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO> users_;
    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO> getUsersList() {
      return users_;
    }
    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder> 
        getUsersOrBuilderList() {
      return users_;
    }
    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    @java.lang.Override
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <code>repeated .UserResponseDTO users = 1;</code>
     */
    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder getUsersOrBuilder(
        int index) {
      return users_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < users_.size(); i++) {
        output.writeMessage(1, users_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < users_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, users_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog)) {
        return super.equals(obj);
      }
      com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog other = (com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog) obj;

      if (!getUsersList()
          .equals(other.getUsersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUsersCount() > 0) {
        hash = (37 * hash) + USERS_FIELD_NUMBER;
        hash = (53 * hash) + getUsersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserResponseCatalog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserResponseCatalog)
        com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseCatalog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseCatalog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog.class, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog.Builder.class);
      }

      // Construct using com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
        } else {
          users_ = null;
          usersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.internal_static_UserResponseCatalog_descriptor;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog getDefaultInstanceForType() {
        return com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog.getDefaultInstance();
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog build() {
        com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog buildPartial() {
        com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog result = new com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog result) {
        if (usersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            users_ = java.util.Collections.unmodifiableList(users_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.users_ = users_;
        } else {
          result.users_ = usersBuilder_.build();
        }
      }

      private void buildPartial0(com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog) {
          return mergeFrom((com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog other) {
        if (other == com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog.getDefaultInstance()) return this;
        if (usersBuilder_ == null) {
          if (!other.users_.isEmpty()) {
            if (users_.isEmpty()) {
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUsersIsMutable();
              users_.addAll(other.users_);
            }
            onChanged();
          }
        } else {
          if (!other.users_.isEmpty()) {
            if (usersBuilder_.isEmpty()) {
              usersBuilder_.dispose();
              usersBuilder_ = null;
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
              usersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUsersFieldBuilder() : null;
            } else {
              usersBuilder_.addAllMessages(other.users_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO m =
                    input.readMessage(
                        com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.parser(),
                        extensionRegistry);
                if (usersBuilder_ == null) {
                  ensureUsersIsMutable();
                  users_.add(m);
                } else {
                  usersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO> users_ =
        java.util.Collections.emptyList();
      private void ensureUsersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          users_ = new java.util.ArrayList<com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO>(users_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder> usersBuilder_;

      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public java.util.List<com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO> getUsersList() {
        if (usersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(users_);
        } else {
          return usersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public int getUsersCount() {
        if (usersBuilder_ == null) {
          return users_.size();
        } else {
          return usersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO getUsers(int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);
        } else {
          return usersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public Builder setUsers(
          int index, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.set(index, value);
          onChanged();
        } else {
          usersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public Builder setUsers(
          int index, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.set(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public Builder addUsers(com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(value);
          onChanged();
        } else {
          usersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public Builder addUsers(
          int index, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(index, value);
          onChanged();
        } else {
          usersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public Builder addUsers(
          com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public Builder addUsers(
          int index, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public Builder addAllUsers(
          java.lang.Iterable<? extends com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO> values) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, users_);
          onChanged();
        } else {
          usersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public Builder clearUsers() {
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          usersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public Builder removeUsers(int index) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.remove(index);
          onChanged();
        } else {
          usersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder getUsersBuilder(
          int index) {
        return getUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder getUsersOrBuilder(
          int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);  } else {
          return usersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public java.util.List<? extends com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder> 
           getUsersOrBuilderList() {
        if (usersBuilder_ != null) {
          return usersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(users_);
        }
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder addUsersBuilder() {
        return getUsersFieldBuilder().addBuilder(
            com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder addUsersBuilder(
          int index) {
        return getUsersFieldBuilder().addBuilder(
            index, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .UserResponseDTO users = 1;</code>
       */
      public java.util.List<com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder> 
           getUsersBuilderList() {
        return getUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder> 
          getUsersFieldBuilder() {
        if (usersBuilder_ == null) {
          usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTO.Builder, com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseDTOOrBuilder>(
                  users_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          users_ = null;
        }
        return usersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:UserResponseCatalog)
    }

    // @@protoc_insertion_point(class_scope:UserResponseCatalog)
    private static final com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog();
    }

    public static com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserResponseCatalog>
        PARSER = new com.google.protobuf.AbstractParser<UserResponseCatalog>() {
      @java.lang.Override
      public UserResponseCatalog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserResponseCatalog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserResponseCatalog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.conveniencestore.conveniencestore.protobuf.UserResponseDto.UserResponseCatalog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserResponseDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserResponseDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserResponseCatalog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserResponseCatalog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027user_response_dto.proto\032\020user_roles.pr" +
      "oto\032\025local_date_time.proto\"\240\001\n\017UserRespo" +
      "nseDTO\022\n\n\002id\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\022\r\n\005" +
      "email\030\003 \001(\t\022\030\n\004role\030\004 \001(\0162\n.UserRoles\022\"\n" +
      "\ncreated_at\030\005 \001(\0132\016.LocalDateTime\022\"\n\nupd" +
      "ated_at\030\006 \001(\0132\016.LocalDateTime\"6\n\023UserRes" +
      "ponseCatalog\022\037\n\005users\030\001 \003(\0132\020.UserRespon" +
      "seDTOB0\n.com.conveniencestore.convenienc" +
      "estore.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.getDescriptor(),
          com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.getDescriptor(),
        });
    internal_static_UserResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserResponseDTO_descriptor,
        new java.lang.String[] { "Id", "Username", "Email", "Role", "CreatedAt", "UpdatedAt", });
    internal_static_UserResponseCatalog_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserResponseCatalog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserResponseCatalog_descriptor,
        new java.lang.String[] { "Users", });
    descriptor.resolveAllFeaturesImmutable();
    com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.getDescriptor();
    com.conveniencestore.conveniencestore.protobuf.LocalDateTimeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
