// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_roles.proto
// Protobuf Java Version: 4.29.0

package com.conveniencestore.conveniencestore.protobuf;

public final class UserRolesOuterClass {
  private UserRolesOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      UserRolesOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code UserRoles}
   */
  public enum UserRoles
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADMIN = 0;</code>
     */
    ADMIN(0),
    /**
     * <code>EMPLOYEE = 1;</code>
     */
    EMPLOYEE(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        UserRoles.class.getName());
    }
    /**
     * <code>ADMIN = 0;</code>
     */
    public static final int ADMIN_VALUE = 0;
    /**
     * <code>EMPLOYEE = 1;</code>
     */
    public static final int EMPLOYEE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserRoles valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UserRoles forNumber(int value) {
      switch (value) {
        case 0: return ADMIN;
        case 1: return EMPLOYEE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserRoles>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserRoles> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserRoles>() {
            public UserRoles findValueByNumber(int number) {
              return UserRoles.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.conveniencestore.conveniencestore.protobuf.UserRolesOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserRoles[] VALUES = values();

    public static UserRoles valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserRoles(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:UserRoles)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020user_roles.proto*$\n\tUserRoles\022\t\n\005ADMIN" +
      "\020\000\022\014\n\010EMPLOYEE\020\001B0\n.com.conveniencestore" +
      ".conveniencestore.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
