# PATHS


#! JSON REPORT
##? CONTROL PATHS

# CREATE USERS
JSON_CREATE_USER_REPORT_PATH_1 = './Control_Project_JSON/k6/json_create_user/json_create_user_report_k6_1/json_create_user_report_1.csv'
JSON_CREATE_USER_REPORT_PATH_2 = './Control_Project_JSON/k6/json_create_user/json_create_user_report_k6_2/json_create_user_report_2.csv'
JSON_CREATE_USER_REPORT_PATH_3 = './Control_Project_JSON/k6/json_create_user/json_create_user_report_k6_3/json_create_user_report_3.csv'

# GET ALL USERS
JSON_GET_ALL_USERS_REPORT_PATH_1 = './Control_Project_JSON/k6/json_get_all_users/json_get_all_users_report_k6_1/json_get_all_users_report_1.csv'
JSON_GET_ALL_USERS_REPORT_PATH_2 = './Control_Project_JSON/k6/json_get_all_users/json_get_all_users_report_k6_2/json_get_all_users_report_2.csv'
JSON_GET_ALL_USERS_REPORT_PATH_3 = './Control_Project_JSON/k6/json_get_all_users//json_get_all_users_report_k6_3/json_get_all_users_report_3.csv'

# GET USER BY ID
JSON_GET_USER_ID_REPORT_PATH_1 = './Control_Project_JSON/k6/json_get_user_id/json_get_user_id_report_k6_1/json_get_user_id_report_1.csv'
JSON_GET_USER_ID_REPORT_PATH_2 = './Control_Project_JSON/k6/json_get_user_id/json_get_user_id_report_k6_2/json_get_user_id_report_2.csv'
JSON_GET_USER_ID_REPORT_PATH_3 = './Control_Project_JSON/k6/json_get_user_id/json_get_user_id_report_k6_3/json_get_user_id_report_3.csv'


# GET ALL PRODUCT ENTITIES
JSON_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_1 = './Control_Project_JSON/k6/json_get_all_products_entities/json_get_all_product_entities_report_k6_1/json_get_all_product_entities_report_1.csv'
JSON_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_2 = './Control_Project_JSON/k6/json_get_all_products_entities/json_get_all_product_entities_report_k6_2/json_get_all_product_entities_report_2.csv'
JSON_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_3 = './Control_Project_JSON/k6/json_get_all_products_entities//json_get_all_product_entities_report_k6_3/json_get_all_product_entities_report_3.csv'


##? CONTROL POD PATHS
JSON_CREATE_USER_POD_REPORT_PATH_1 = './Control_Project_JSON/k6/json_create_user/json_create_user_report_k6_1/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_17_35_05.csv'
JSON_CREATE_USER_POD_REPORT_PATH_2 = './Control_Project_JSON/k6/json_create_user/json_create_user_report_k6_2/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_18_09_32.csv'
JSON_CREATE_USER_POD_REPORT_PATH_3 = './Control_Project_JSON/k6/json_create_user/json_create_user_report_k6_3/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_18_46_24.csv'

# GET ALL USERS
JSON_GET_ALL_USERS_POD_REPORT_PATH_1 = './Control_Project_JSON/k6/json_get_all_users/json_get_all_users_report_k6_1/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_16_42_16.csv'
JSON_GET_ALL_USERS_POD_REPORT_PATH_2 = './Control_Project_JSON/k6/json_get_all_users/json_get_all_users_report_k6_2/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_16_45_38.csv'
JSON_GET_ALL_USERS_POD_REPORT_PATH_3 = './Control_Project_JSON/k6/json_get_all_users//json_get_all_users_report_k6_3/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_16_48_45.csv'

# GET USER BY ID
JSON_GET_USER_ID_POD_REPORT_PATH_1 = './Control_Project_JSON/k6/json_get_user_id/json_get_user_id_report_k6_1/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_16_30_57.csv'
JSON_GET_USER_ID_POD_REPORT_PATH_2 = './Control_Project_JSON/k6/json_get_user_id/json_get_user_id_report_k6_2/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_16_33_39.csv'
JSON_GET_USER_ID_POD_REPORT_PATH_3 = './Control_Project_JSON/k6/json_get_user_id/json_get_user_id_report_k6_3/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_16_36_34.csv'


# GET ALL PRODUCT ENTITIES
JSON_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_1 = './Control_Project_JSON/k6/json_get_all_products_entities/json_get_all_product_entities_report_k6_1/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_16_54_37.csv'
JSON_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_2 = './Control_Project_JSON/k6/json_get_all_products_entities/json_get_all_product_entities_report_k6_2/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_16_57_31.csv'
JSON_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_3 = './Control_Project_JSON/k6/json_get_all_products_entities//json_get_all_product_entities_report_k6_3/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_01_17_00_23.csv'


#! PROTOBUF REPORT
##? CONTROL PATHS

# CREATE USERS
PROTOBUF_CREATE_USER_REPORT_PATH_1 = './Experimental_Group_ProtoBuff/k6/protobuf_create_user/protobuf_create_users_report_k6_1/protobuf_create_user_report_1.csv'
PROTOBUF_CREATE_USER_REPORT_PATH_2 = './Experimental_Group_ProtoBuff/k6/protobuf_create_user/protobuf_create_users_report_k6_2/protobuf_create_user_report_2.csv'
PROTOBUF_CREATE_USER_REPORT_PATH_3 = './Experimental_Group_ProtoBuff/k6/protobuf_create_user/protobuf_create_users_report_k6_3/protobuf_create_user_report_3.csv'

# GET ALL USERS
PROTOBUF_GET_ALL_USERS_REPORT_PATH_1 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_users/protobuf_get_all_users_report_k6_1/protobuf_get_all_user_report_1.csv'
PROTOBUF_GET_ALL_USERS_REPORT_PATH_2 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_users/protobuf_get_all_users_report_k6_2/protobuf_get_all_user_report_2.csv'
PROTOBUF_GET_ALL_USERS_REPORT_PATH_3 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_users/protobuf_get_all_users_report_k6_3/protobuf_get_all_user_report_3.csv'

# GET USER BY ID
PROTOBUF_GET_USER_ID_REPORT_PATH_1 = './Experimental_Group_ProtoBuff/k6/protobuf_get_user_id/protobuf_get_user_id_report_k6_1/protobuf_get_user_report_1.csv'
PROTOBUF_GET_USER_ID_REPORT_PATH_2 = './Experimental_Group_ProtoBuff/k6/protobuf_get_user_id/protobuf_get_user_id_report_k6_2/protobuf_get_user_report_2.csv'
PROTOBUF_GET_USER_ID_REPORT_PATH_3 = './Experimental_Group_ProtoBuff/k6/protobuf_get_user_id/protobuf_get_user_id_report_k6_3/protobuf_get_user_report_3.csv'


# GET ALL PRODUCT ENTITIES
PROTOBUF_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_1 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_products_entities/protobuf_get_all_product_entities_report_k6_1/protobuf_get_all_product_entities_report_1.csv'
PROTOBUF_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_2 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_products_entities/protobuf_get_all_product_entities_report_k6_2/protobuf_get_all_product_entities_report_2.csv'
PROTOBUF_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_3 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_products_entities/protobuf_get_all_product_entities_report_k6_3/protobuf_get_all_product_entities_report_3.csv'


##? CONTROL POD PATHS
PROTOBUF_CREATE_USER_POD_REPORT_PATH_1 = './Experimental_Group_ProtoBuff/k6/protobuf_create_user/protobuf_create_users_report_k6_1/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_03_12_17_18.csv'
PROTOBUF_CREATE_USER_POD_REPORT_PATH_2 = './Experimental_Group_ProtoBuff/k6/protobuf_create_user/protobuf_create_users_report_k6_2/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_03_14_00_12.csv'
PROTOBUF_CREATE_USER_POD_REPORT_PATH_3 = './Experimental_Group_ProtoBuff/k6/protobuf_create_user/protobuf_create_users_report_k6_3/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_03_14_39_07.csv'

# GET ALL USERS
PROTOBUF_GET_ALL_USERS_POD_REPORT_PATH_1 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_users/protobuf_get_all_users_report_k6_1/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_02_20_51_32.csv'
PROTOBUF_GET_ALL_USERS_POD_REPORT_PATH_2 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_users/protobuf_get_all_users_report_k6_2/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_02_20_54_08.csv'
PROTOBUF_GET_ALL_USERS_POD_REPORT_PATH_3 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_users/protobuf_get_all_users_report_k6_3/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_02_20_57_23.csv'

# GET USER BY ID
PROTOBUF_GET_USER_ID_POD_REPORT_PATH_1 = './Experimental_Group_ProtoBuff/k6/protobuf_get_user_id/protobuf_get_user_id_report_k6_1/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_02_19_16_21.csv'
PROTOBUF_GET_USER_ID_POD_REPORT_PATH_2 = './Experimental_Group_ProtoBuff/k6/protobuf_get_user_id/protobuf_get_user_id_report_k6_2/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_02_19_19_02.csv'
PROTOBUF_GET_USER_ID_POD_REPORT_PATH_3 = './Experimental_Group_ProtoBuff/k6/protobuf_get_user_id/protobuf_get_user_id_report_k6_3/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_02_19_21_07.csv'


# GET ALL PRODUCT ENTITIES
PROTOBUF_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_1 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_products_entities/protobuf_get_all_product_entities_report_k6_1/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_02_21_00_48.csv'
PROTOBUF_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_2 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_products_entities/protobuf_get_all_product_entities_report_k6_2/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_02_21_03_05.csv'
PROTOBUF_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_3 = './Experimental_Group_ProtoBuff/k6/protobuf_get_all_products_entities/protobuf_get_all_product_entities_report_k6_3/Pod_Process_Power_Consumption_(W)_in_Namespace_app_namespace_data_as_joinbyfield_2025_03_02_21_05_57.csv'



#! CSV COLUMNS NAMES
##? NORMAL REPORTS
METRIC_NAME = 'metric_name'
TIMESTAP = 'timestamp'
METRIC_VALUE = 'metric_value'
CHECK = 'check'
ERROR = 'error'
ERROR_CODE = 'error_code'
EXPECTED_RESPONSE = 'expected_response'
GROUP = 'group'
METHOD = 'method'
NAME = 'name'
PROTO = 'proto'
SCENARIO = 'scenario'
SERVICE = 'service'
STATUS = 'status'
SUBPROTO = 'subproto'
TLS_VERSION = 'tls_version'
URL = 'url'
EXTRA_TAGS = 'extra_tags'
METADATA = 'metadata'


##? POD REPORTS
PKG = 'PKG'
DRAM = 'DRAM'
OTHER = 'OTHER'
GPU = 'GPU'

#! CSV ROW NAMES
##? NORMAL REPORTS

HTTP_REQS = 'http_reqs'
HTTP_REQ_DURATION = 'http_req_duration'
HTTP_REQ_BLOCKED = 'http_req_blocked'
HTTP_REQ_CONNECTING = 'http_req_connecting'
HTTP_REQ_TLS_HANDSHAKING = 'http_req_tls_handshaking'
HTTP_REQ_SENDING = 'http_req_sending'
HTTP_REQ_WAITING = 'http_req_waiting'
HTTP_REQ_RECEIVING = 'http_req_receiving'
HTTP_REQ_FAILED = 'http_req_failed'
RESPONSE_TIME = 'response_time'
RESPONSE_SIZE = 'response_size'
REPONSE_SIZE = 'reponse_size' #! type from changing scripts
CHECKS = 'checks'
DATA_SENT = 'data_sent'
DATA_RECEIVED = 'data_received'
ITERATION_DURATION = 'iteration_duration'

