apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gateway-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 1230199/gateway:latest
          ports:
            - containerPort: 8082
              name: web
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "700m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gateway-namespace
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8082
      targetPort: 8082
      name: web
