apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
        - name: nginx
          image: nginx:1.22.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config-map  # This is a ConfigMap containing your nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-svc
spec:
  selector:
    app: nginx-lb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
