apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-command
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: votes-command
  template:
    metadata:
      labels:
        app: votes-command
    spec:
      containers:
        - name: votes-command
          image: rodrigo1230207/votes_command
          ports:
            - containerPort: 9092
          resources:
            limits:
              cpu: "300m"  # Increase the CPU limit to 500 milliCPU
              memory: "300Mi"  # Increase the memory limit to 500 Mi
---
apiVersion: v1
kind: Service
metadata:
  name: votes-command-svc
spec:
  type: LoadBalancer
  selector:
    app: votes-command
  ports:
    - port: 9092
      targetPort: 9092