// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProductDTO.proto
// Protobuf Java Version: 4.29.0

package com.isep.acme.protobuf;

public final class ProductDTOOuterClass {
  private ProductDTOOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      ProductDTOOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sku = 1;</code>
     * @return The sku.
     */
    java.lang.String getSku();
    /**
     * <code>string sku = 1;</code>
     * @return The bytes for sku.
     */
    com.google.protobuf.ByteString
        getSkuBytes();

    /**
     * <code>string designation = 2;</code>
     * @return The designation.
     */
    java.lang.String getDesignation();
    /**
     * <code>string designation = 2;</code>
     * @return The bytes for designation.
     */
    com.google.protobuf.ByteString
        getDesignationBytes();
  }
  /**
   * Protobuf type {@code ProductDTO}
   */
  public static final class ProductDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProductDTO)
      ProductDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        ProductDTO.class.getName());
    }
    // Use ProductDTO.newBuilder() to construct.
    private ProductDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProductDTO() {
      sku_ = "";
      designation_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.class, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder.class);
    }

    public static final int SKU_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sku_ = "";
    /**
     * <code>string sku = 1;</code>
     * @return The sku.
     */
    @java.lang.Override
    public java.lang.String getSku() {
      java.lang.Object ref = sku_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sku_ = s;
        return s;
      }
    }
    /**
     * <code>string sku = 1;</code>
     * @return The bytes for sku.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSkuBytes() {
      java.lang.Object ref = sku_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sku_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESIGNATION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object designation_ = "";
    /**
     * <code>string designation = 2;</code>
     * @return The designation.
     */
    @java.lang.Override
    public java.lang.String getDesignation() {
      java.lang.Object ref = designation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        designation_ = s;
        return s;
      }
    }
    /**
     * <code>string designation = 2;</code>
     * @return The bytes for designation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDesignationBytes() {
      java.lang.Object ref = designation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        designation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sku_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, sku_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(designation_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, designation_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sku_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sku_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(designation_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, designation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO)) {
        return super.equals(obj);
      }
      com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO other = (com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO) obj;

      if (!getSku()
          .equals(other.getSku())) return false;
      if (!getDesignation()
          .equals(other.getDesignation())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SKU_FIELD_NUMBER;
      hash = (53 * hash) + getSku().hashCode();
      hash = (37 * hash) + DESIGNATION_FIELD_NUMBER;
      hash = (53 * hash) + getDesignation().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductDTO)
        com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.class, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder.class);
      }

      // Construct using com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sku_ = "";
        designation_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductDTO_descriptor;
      }

      @java.lang.Override
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO getDefaultInstanceForType() {
        return com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO build() {
        com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO buildPartial() {
        com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO result = new com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sku_ = sku_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.designation_ = designation_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO) {
          return mergeFrom((com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO other) {
        if (other == com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.getDefaultInstance()) return this;
        if (!other.getSku().isEmpty()) {
          sku_ = other.sku_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDesignation().isEmpty()) {
          designation_ = other.designation_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                sku_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                designation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object sku_ = "";
      /**
       * <code>string sku = 1;</code>
       * @return The sku.
       */
      public java.lang.String getSku() {
        java.lang.Object ref = sku_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sku_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sku = 1;</code>
       * @return The bytes for sku.
       */
      public com.google.protobuf.ByteString
          getSkuBytes() {
        java.lang.Object ref = sku_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sku_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sku = 1;</code>
       * @param value The sku to set.
       * @return This builder for chaining.
       */
      public Builder setSku(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sku_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string sku = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSku() {
        sku_ = getDefaultInstance().getSku();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string sku = 1;</code>
       * @param value The bytes for sku to set.
       * @return This builder for chaining.
       */
      public Builder setSkuBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sku_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object designation_ = "";
      /**
       * <code>string designation = 2;</code>
       * @return The designation.
       */
      public java.lang.String getDesignation() {
        java.lang.Object ref = designation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          designation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string designation = 2;</code>
       * @return The bytes for designation.
       */
      public com.google.protobuf.ByteString
          getDesignationBytes() {
        java.lang.Object ref = designation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          designation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string designation = 2;</code>
       * @param value The designation to set.
       * @return This builder for chaining.
       */
      public Builder setDesignation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        designation_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string designation = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDesignation() {
        designation_ = getDefaultInstance().getDesignation();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string designation = 2;</code>
       * @param value The bytes for designation to set.
       * @return This builder for chaining.
       */
      public Builder setDesignationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        designation_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProductDTO)
    }

    // @@protoc_insertion_point(class_scope:ProductDTO)
    private static final com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO();
    }

    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductDTO>
        PARSER = new com.google.protobuf.AbstractParser<ProductDTO>() {
      @java.lang.Override
      public ProductDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProductDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductCatalogDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductCatalogDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    java.util.List<com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO> 
        getProductsList();
    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO getProducts(int index);
    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    int getProductsCount();
    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    java.util.List<? extends com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder> 
        getProductsOrBuilderList();
    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder getProductsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProductCatalogDTO}
   */
  public static final class ProductCatalogDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProductCatalogDTO)
      ProductCatalogDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        ProductCatalogDTO.class.getName());
    }
    // Use ProductCatalogDTO.newBuilder() to construct.
    private ProductCatalogDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProductCatalogDTO() {
      products_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductCatalogDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductCatalogDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO.class, com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO.Builder.class);
    }

    public static final int PRODUCTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO> products_;
    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO> getProductsList() {
      return products_;
    }
    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder> 
        getProductsOrBuilderList() {
      return products_;
    }
    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    @java.lang.Override
    public int getProductsCount() {
      return products_.size();
    }
    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    @java.lang.Override
    public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO getProducts(int index) {
      return products_.get(index);
    }
    /**
     * <code>repeated .ProductDTO products = 1;</code>
     */
    @java.lang.Override
    public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder getProductsOrBuilder(
        int index) {
      return products_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < products_.size(); i++) {
        output.writeMessage(1, products_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < products_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, products_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO)) {
        return super.equals(obj);
      }
      com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO other = (com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO) obj;

      if (!getProductsList()
          .equals(other.getProductsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductsCount() > 0) {
        hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
        hash = (53 * hash) + getProductsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductCatalogDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductCatalogDTO)
        com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductCatalogDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductCatalogDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO.class, com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO.Builder.class);
      }

      // Construct using com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
        } else {
          products_ = null;
          productsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.isep.acme.protobuf.ProductDTOOuterClass.internal_static_ProductCatalogDTO_descriptor;
      }

      @java.lang.Override
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO getDefaultInstanceForType() {
        return com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO build() {
        com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO buildPartial() {
        com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO result = new com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO result) {
        if (productsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            products_ = java.util.Collections.unmodifiableList(products_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.products_ = products_;
        } else {
          result.products_ = productsBuilder_.build();
        }
      }

      private void buildPartial0(com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO) {
          return mergeFrom((com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO other) {
        if (other == com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO.getDefaultInstance()) return this;
        if (productsBuilder_ == null) {
          if (!other.products_.isEmpty()) {
            if (products_.isEmpty()) {
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductsIsMutable();
              products_.addAll(other.products_);
            }
            onChanged();
          }
        } else {
          if (!other.products_.isEmpty()) {
            if (productsBuilder_.isEmpty()) {
              productsBuilder_.dispose();
              productsBuilder_ = null;
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProductsFieldBuilder() : null;
            } else {
              productsBuilder_.addAllMessages(other.products_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO m =
                    input.readMessage(
                        com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.parser(),
                        extensionRegistry);
                if (productsBuilder_ == null) {
                  ensureProductsIsMutable();
                  products_.add(m);
                } else {
                  productsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO> products_ =
        java.util.Collections.emptyList();
      private void ensureProductsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          products_ = new java.util.ArrayList<com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO>(products_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder> productsBuilder_;

      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public java.util.List<com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO> getProductsList() {
        if (productsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(products_);
        } else {
          return productsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public int getProductsCount() {
        if (productsBuilder_ == null) {
          return products_.size();
        } else {
          return productsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO getProducts(int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);
        } else {
          return productsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public Builder setProducts(
          int index, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.set(index, value);
          onChanged();
        } else {
          productsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public Builder setProducts(
          int index, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.set(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public Builder addProducts(com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(value);
          onChanged();
        } else {
          productsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public Builder addProducts(
          int index, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(index, value);
          onChanged();
        } else {
          productsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public Builder addProducts(
          com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public Builder addProducts(
          int index, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public Builder addAllProducts(
          java.lang.Iterable<? extends com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO> values) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, products_);
          onChanged();
        } else {
          productsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public Builder clearProducts() {
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public Builder removeProducts(int index) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.remove(index);
          onChanged();
        } else {
          productsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder getProductsBuilder(
          int index) {
        return getProductsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder getProductsOrBuilder(
          int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);  } else {
          return productsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public java.util.List<? extends com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder> 
           getProductsOrBuilderList() {
        if (productsBuilder_ != null) {
          return productsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(products_);
        }
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder addProductsBuilder() {
        return getProductsFieldBuilder().addBuilder(
            com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder addProductsBuilder(
          int index) {
        return getProductsFieldBuilder().addBuilder(
            index, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductDTO products = 1;</code>
       */
      public java.util.List<com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder> 
           getProductsBuilderList() {
        return getProductsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder> 
          getProductsFieldBuilder() {
        if (productsBuilder_ == null) {
          productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTO.Builder, com.isep.acme.protobuf.ProductDTOOuterClass.ProductDTOOrBuilder>(
                  products_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          products_ = null;
        }
        return productsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProductCatalogDTO)
    }

    // @@protoc_insertion_point(class_scope:ProductCatalogDTO)
    private static final com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO();
    }

    public static com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductCatalogDTO>
        PARSER = new com.google.protobuf.AbstractParser<ProductCatalogDTO>() {
      @java.lang.Override
      public ProductCatalogDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProductCatalogDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductCatalogDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.isep.acme.protobuf.ProductDTOOuterClass.ProductCatalogDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductCatalogDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductCatalogDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ProductDTO.proto\".\n\nProductDTO\022\013\n\003sku\030" +
      "\001 \001(\t\022\023\n\013designation\030\002 \001(\t\"2\n\021ProductCat" +
      "alogDTO\022\035\n\010products\030\001 \003(\0132\013.ProductDTOB\030" +
      "\n\026com.isep.acme.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProductDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProductDTO_descriptor,
        new java.lang.String[] { "Sku", "Designation", });
    internal_static_ProductCatalogDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductCatalogDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProductCatalogDTO_descriptor,
        new java.lang.String[] { "Products", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
